ci: Build wheels in separate workflow
thaler-lab/EnergyFlow pull request #43
Opened 2024-07-07 10:34 UTC by j-s-ashley

Addresses part of #31:

> - [ ] Split the CI components from the wheel building in CI
> c.f. https://github.com/thaler-lab/Wasserstein/pull/8
> - [ ] Have the wheel building workflows run and [upload the wheels to GitHub Actions as an artifact](https://learn.scientific-python.org/development/guides/gha-wheels/#the-core-job-3-main-oss)

2024-08-07 18:25 UTC, matthewfeickert requested changes
Looks good beyond some very small changes.

Totally optional but you can also add some visual checks that will show up in the logs (probably post `twine check`) with

```yaml
    - name: List contents of sdist
      run: python -m tarfile --list dist/*.tar.gz

    - name: List contents of wheel
      run: python -m zipfile --list dist/*.whl
```

2024-08-07 18:25 UTC, matthewfeickert commented on .github/workflows/build-wheels.yml
> +        uses: actions/setup-python@v4
```suggestion
        uses: actions/setup-python@v5
```

Not your fault, but you've been patiently waiting for review so long that there's a new version out. :sweat_smile:

2024-08-07 18:25 UTC, matthewfeickert commented on .github/workflows/build-wheels.yml
> +        run: pipx run twine check dist/*
```suggestion
        run: pipx run twine check --strict dist/*
```

`twine` has a strict option.

```console
$ pipx run twine check --help
usage: twine check [-h] [--strict] dist [dist ...]

positional arguments:
  dist        The distribution files to check, usually dist/*

options:
  -h, --help  show this help message and exit
  --strict    Fail on warnings
```

2024-08-08 16:20 UTC, matthewfeickert reviewed
LGTM. Just 1 nitpick suggestion.

2024-08-08 16:33 UTC, j-s-ashley commented on .github/workflows/build-wheels.yml
> +        run: python -m zipfile --list dist/*.whl
Gotcha. No, that makes a lot of sense. Thanks!

2024-08-08 16:34 UTC, matthewfeickert approved these changes

2024-08-08 17:32 UTC, merged